spring:
  jpa:
  show-sql: true
  properties:
    hibernate:
      hbm2ddl:
        auto: update
server:
  connection-timeout: 2000


management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true

